# Serving
port                : 4000
host                : 0.0.0.0

# Info Blog
title: Inside Block
call: "Os códigos estão dentro do bloco"
description: >-
  Os códigos estão dentro do bloco. Dicas e tutoriais sobre tecnologia, desenvolvimento web, SEO, otimização, monetização, blogs, redes sociais e muito mais!
keywords: >-
  Git, GitHub Pages, GitLab Pages, HTTPS, SEO, HTML, CSS, XML, React, ReactJS, React Native, JavaScript, JS, Tecnologia, SQL, PHP.
logo: /assets/logo/logo.png
favicon: /assets/logo/favicon.png
author: Inside Block
web_designer: Ediano Silva Santos

# URL Páginations
url: 'https://insideblock.com'
baseurl: ''
#paginate_path: '/page/:num/'
permalink: '/blog/:title/'
pagination:
  enabled: true
  per_page: 12
  permalink: '/blog/page/:num/'
  sort_reverse: true
  sort_field: 'date'
  title: 'Página :num'
  trail:
    before: 2
    after: 2

# Jekyll Plugins and Tools
markdown: kramdown
highlighter: rouge
plugins: ['jekyll-paginate-v2','jekyll-sitemap']

# Include # Collections
collections:
  authors:
  pages:
    output: true
    permalink: /:path
  category:
    output: true
    permalink: /:path

# Offline
files_to_cache:
  - '/assets/logo/favicon.png'

pages_to_cache:
  - '/offline'

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Verification
g_analytics: 'UA-81236717-1'
g_tagmanager: 'GTM-NHBPTTD'
g_optimize: 'GTM-TH6M3G8'

# Netlify
include: ['_redirects','_headers']

# Jekyll admin
jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration

# Remove pagination from sitemap
defaults:
  - scope:
      path: '/blog/page/'
    values:
      sitemap: false
      title: 'Página :num'
      