backend:
  name: gitlab
  repo: insideblock/insideblock.com
  branch: master
  site_domain: insideblock.com

logo_url: /assets/logo/logo.png
media_folder: "assets/blog"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "post" # Posts
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date Publish", name: "datePublished", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Date Modified", name: "dateModified", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "select", options:
          ["comunicado", "css", "dev", "js", "jekyll", "misc", "sponsorship"], required: false}
      
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image Source", name: "image_source", widget: "select", options: 
          ["Inside Block", "Pixabay", "Google Imagens", "Dillinger"], required: false}

      - {label: "Author", name: "author", widget: "select", options: 
          ["Ediano Silva Santos", "Danielli Carvalho", "Luciana Fabiano"]}

      - {label: "Coauthor", name: "coauthor", widget: "select", options: 
          ["Ediano Silva Santos", "Danielli Carvalho", "Luciana Fabiano"], required: false}
          
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - {label: "Ads", name: "ads", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}



  - name: "page" # Pages
    label: "Pages"
    folder: "_pages"
    extension: "html"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["compress", "page", "default"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Sitemap index", name: "sitemap", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}



  - name: "categories" # Category
    label: "Categories"
    folder: "_category"
    extension: "md"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Sitemap index", name: "sitemap", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}



  - name: "data" # Data
    label: "Navegação"
    folder: "_data"
    extension: "yml"
    create: true
    slug: "{{slug}}"
    fields:          
      - {label: "Nome do arquivo", name: "title", widget: "string"}

      - label: 'Crie a sua lista'
        name: 'list'
        widget: 'list'
        required: false
        types:
          - label: 'Inserir lista de páginas'
            name: 'list-link'
            widget: 'list'
            fields:
              - { label: 'Name da página', name: 'page', widget: 'string', required: false}
              - { label: 'Link da página', name: 'link', widget: 'string', required: false}
              - { label: 'Descrição da página', name: 'desc', widget: 'string', required: false}
              - { label: 'Nome do icon', name: 'icon', widget: 'string', required: false}
              - { label: 'Target', name: 'target', widget: "select", options: ["_black"], required: false}
              - { label: 'Class', name: 'class', widget: 'string', required: false}
